### ISSUE TITLE
Still not syncing

### ISSUE THREAD

**Issue by joshpitzalis** [davecahill/beesight#2]
I am using a mac. I just installed python. cd'd into a clone of this repo, added my credentials and changed the name of the config file and then ran `python beesight.py'.

It says 'ImportError: No module named requests`

I just meditated for 10 minutes to  make sure there was data to sync before hand.

Am I doing something wrong?

<img width="842" alt="screen shot 2016-02-27 at 11 31 57" src="https://cloud.githubusercontent.com/assets/10258114/13371192/33f48c4a-dd46-11e5-903c-46e697981286.png">

**Comment by davecahill** [comment]
Hi Josh!

That message means you need to install the python [requests](http://docs.python-requests.org/en/master/) library by running:

```
pip install requests
```

Further instructions here:
http://docs.python-requests.org/en/master/user/install/

I guess my readme instructions are pretty basic - I wasn't sure if anyone would be interested in using it. :) Will see what I can do to make them clearer.

**Comment by joshpitzalis** [comment]
Ran through it, got python properly installed, then installed pip.

Now it just spits out

```
Joshuas-MacBook-2:beesight josh$ python beesight.py
Traceback (most recent call last):
  File "beesight.py", line 4, in <module>
    import urllib2
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
Joshuas-MacBook-2:beesight josh$ 
```

I'm not expecting you to help. Thank you for being so incredible this far. Just thought you'd like to know.

I don't speak python so I'm afraid i can't work on a pull request. Maybe one day :)

**Comment by davecahill** [comment]
Looks like this is some brew python weirdness unrelated to the specific code in this repo - I took a quick look to see if I could get you unstuck though. :)

Here is a StackOverflow post which discusses the issue you see: http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder-trying-to-register-a-packa

Looks like running the below command and trying again, or logging out and back in, may fix things:

```
hash -r python
```
